[build]
  command = "npm run build"
  publish = "dist"

# ðŸ”´ PROXY API (PRIMERO)
[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbxos5-UZqu7QwYhShw5pdbo2sJewfzt6JWyWiePU3vH8iw1WErDyyWw6nNeGkDAI8bS/exec"
  status = 200
  force = true

# ðŸŸ¢ SPA fallback (SEGUNDO)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
