[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbwyKxdj4MNmwlD4NhGY9Wq7LijwiugXGLemzR09MSCdWDyocA3pFBl1GAWaSxbT00eL/exec"
  status = 200
  force = true

# SPA fallback (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
